import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service - SIXARMS',
  description: 'Terms of Service for SIXARMS AI-powered content creation platform',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-white py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-8 gradient-text">Terms of Service</h1>
        
        <div className="prose prose-invert max-w-none space-y-6">
          <p className="text-light-gray">Last updated: {new Date().toLocaleDateString()}</p>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
            <p className="text-light-gray">
              By accessing or using SIXARMS (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). 
              If you disagree with any part of these terms, you may not access the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">2. Description of Service</h2>
            <p className="text-light-gray">
              SIXARMS is an AI-powered content creation platform that helps users generate content for various platforms. 
              The Service includes access to AI models, content generation tools, and related features.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">3. User Accounts</h2>
            <p className="text-light-gray">
              To access certain features of the Service, you must create an account. You are responsible for:
            </p>
            <ul className="list-disc list-inside text-light-gray space-y-2 ml-4">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
              <li>Providing accurate and complete information</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">4. Acceptable Use</h2>
            <p className="text-light-gray">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside text-light-gray space-y-2 ml-4">
              <li>Generate illegal, harmful, or offensive content</li>
              <li>Violate any laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Spam or harass others</li>
              <li>Attempt to gain unauthorized access to the Service</li>
              <li>Reverse engineer or copy the Service</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">5. Content Rights</h2>
            <p className="text-light-gray">
              <strong>Your Content:</strong> You retain all rights to content you create using the Service. 
              You grant us a license to process your input to generate content.
            </p>
            <p className="text-light-gray">
              <strong>Generated Content:</strong> Content generated by our AI is provided under a license for your use. 
              You are responsible for reviewing and editing generated content before use.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">6. Payment and Credits</h2>
            <p className="text-light-gray">
              The Service operates on a credit-based system. Credits are purchased through subscription plans and are 
              non-refundable. Unused credits may expire according to your plan terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">7. Disclaimers</h2>
            <p className="text-light-gray">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THAT THE SERVICE 
              WILL BE ERROR-FREE, UNINTERRUPTED, OR MEET YOUR SPECIFIC REQUIREMENTS.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">8. Limitation of Liability</h2>
            <p className="text-light-gray">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SIXARMS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">9. Termination</h2>
            <p className="text-light-gray">
              We may terminate or suspend your account immediately, without prior notice, for any breach of these Terms. 
              Upon termination, your right to use the Service will cease immediately.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">10. Changes to Terms</h2>
            <p className="text-light-gray">
              We reserve the right to modify these Terms at any time. We will notify users of any material changes 
              via email or through the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-white">11. Contact Information</h2>
            <p className="text-light-gray">
              For questions about these Terms, please contact us at:
              <br />
              Email: legal@sixarms.ai
              <br />
              Address: SIXARMS, Inc., [Your Address]
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10">
          <Link href="/" className="text-coral hover:text-coral-light transition-colors">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  )
}